[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
rust-crypto = "0.2.36"
regex = "1.11.1"
itertools = "0.13.0"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
cached = "0.54.0"
